In [1]:
import numpy as np

In [2]:
def converge(P : np.matrix, epoch = 100, epsilon = 1e-8):
    def diff(A : np.matrix, B: np.matrix):
        if A.shape != B.shape:
            raise Exception("Shape of two matrices are differend")
        else:
            return np.concatenate(np.power(A - B, 2)).sum()
    for i in range(epoch):
        _ = P*P
        if diff(_, P) < epsilon:
            break # convergence
        P = _
        print(P)
    return P
    

In [3]:
# Weather Model

W = np.asmatrix(np.array([
    [0.8, 0.2],
    [0.4, 0.6]
]))

W = converge(W)

with np.printoptions(precision=3, suppress=True):
    print(W)

[[0.72 0.28]
 [0.56 0.44]]
[[0.6752 0.3248]
 [0.6496 0.3504]]
[[0.66688512 0.33311488]
 [0.66622976 0.33377024]]
[[0.66666681 0.33333319]
 [0.66666638 0.33333362]]
[[0.667 0.333]
 [0.667 0.333]]
